### ISSUE TITLE
Player app is not showing textbox to register Player

### ISSUE THREAD

**Issue by anubha661** [fostive/quiz-host-app#75]
Hi,
I followed the steps given in the installation reference document. I am able to host the quiz but not able to play it. 
on entering the URL it just shows Quiz header and rest all is blank. Could you tell me what could be the issue?
Attached is how the player URL is displaying
![Player URL](https://user-images.githubusercontent.com/7997977/92402220-cef20f00-f14c-11ea-84ac-ad03d4aa2d94.JPG)

**Comment by pozil** [comment]
Hi, thanks for trying the quiz. My guess is that there's a configuration error.
Can you check the Heroku logs and your browser console and let me know if there are any errors?

**Comment by anubha661** [comment]
Thank you for the quick response :). It was a configuration issue.  Fixed.
