### ISSUE TITLE
Player App - No Access to QuizPlayerStatsRestResource class

### ISSUE THREAD

**Issue by toddhalfpenny** [fostive/quiz-host-app#81]
### Summary

Error when quiz ends, seen by the players when the app tries to show them their stats at the end of the quiz.

### App Version

Host app version (see bottom of host game page):
2.2.4

Player app version (see bottom of player registration page):
2.0.0

### Steps To Reproduce:

1.  Run a quiz through to the end
1. On the Player app screen you get an error about access to the _QuizPlayerStatsRestResource_ class.

### Expected result

You should see you're personal result (rank etc)

### Actual result

You see an error

### Additional information

I think the `sdfx.QuizPlayerStatsRestResource class` needs to be added to the `Quiz_Host.permissionset` or perhaps have a permission set for the Quiz_Player (to be used by the user that's used by the Heroku app).

**Comment by pozil** [comment]
Hi @toddhalfpenny, thanks for reporting this.

With Winter '21 coming up, we need to assign permissions in order to access Apex classes.
I have anticipated that need since release 2.3.0 so you should be ok if you use the latest version of the host app (2.4.0 at time of writing). Can you confirm?

**Comment by toddhalfpenny** [comment]
Yes, I am using 2.4.0 of the host app. The `QuizPlayerStatsRestResource` class was not in the perm set... I believe it needs to be there.

**Comment by pozil** [comment]
Good catch @toddhalfpenny, you're absolutely right, I forgot that class.
I've just released v2.5.0 with a fix.
