### ISSUE TITLE
Upgrade to latest package fails

### ISSUE THREAD

**Issue by mbaizman** [fostive/quiz-host-app#82]
### Summary

I attempted to upgrade the package and received a "this package does not share a common ancestor" error. 

### App Version

Host app version (see bottom of host game page):
2.2.0

Player app version (see bottom of player registration page):
2.0.0

### Steps To Reproduce:

1.  Click the link to install v2.5 package into an org with v2.2
2.  Wait and see the error

### Expected result

I expected 2.2 to be upgraded to 2.5 If this doesn't upgrade easily, it defeats the purpose of using a package. 

### Actual result

Received an error.

### Additional information

Let me know if I am doing something wrong.

**Comment by pozil** [comment]
Thanks for reporting this Marc.

I messed up when I released the package versions: I didn't specify [package ancestors](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_dev2gp_config_ancestors.htm) (I thought that it was automated).

Unfortunately there's nothing I can do to fix previously released versions (2.5.0.1 and older) but I'll make sure that future versions have ancestors. I'll keep this issue open as a reminder until I release a new version.

**Comment by mbaizman** [comment]
Thanks @pozil, appreciate it. Is the best thing to do to uninstall the previous version completely?

**Comment by pozil** [comment]
Unfortunately, yes. Make sure to export your questions before uninstalling.

**Comment by mbaizman** [comment]
Oh don't worry, I already have!

**Comment by pozil** [comment]
Will be addressed in #84 Spring '21 release (v2.6.0).
Versions from 2.5.0 and onward will be upgradeable.

**Comment by pozil** [comment]
Just released the new version.
