### ISSUE TITLE
Error Install Packege 2.5.0

### ISSUE THREAD

**Issue by JhonatanJJ** [fostive/quiz-host-app#83]
![image](https://user-images.githubusercontent.com/56335033/106504781-673eb680-6495-11eb-965c-c66717e5ccc4.png)

**Comment by pozil** [comment]
Hi @JhonatanJJ,

I have a couple of questions for your in order to assist:
1. what type of Salesforce org is this?
2. is My Domain enabled? (this is required)

**Comment by JhonatanJJ** [comment]
1. what type of Salesforce org is this?
R: those recommended by the guide, https://help.salesforce.com/articleView?id=sf.environment_hub_get_started_my_domain.htm&type=5

2.is My Domain enabled? (this is required)?
R:Yes, I believe it according to the basic procedures in https://developer.salesforce.com/

**Comment by JhonatanJJ** [comment]
I already solved it, the error was in the following. I had created an account with the role of administrator, I created another account with that of developer and I was able to install without problem.

**Comment by pozil** [comment]
Nice, glad to hear that you were able to install. Thanks for trying the quiz app.
