### ISSUE TITLE
Installation on Windows not working

### ISSUE THREAD

**Issue by sandeepepita** [fostive/quiz-host-app#88]
Hello I tried to install application as per steps given in https://github.com/fostive/quiz-host-app?ref=hackernoon.com it works well with "Managed Package" 
but its not working with Scratch Org (for development purposes)
its giving error

Installing Quiz org:
- Org alias:      quiz
- Data:           sample

Cleaning previous scratch org...
Successfully marked scratch org quiz for deletion

Creating scratch org...
WARNING: Warning: If you're using Contacts to Multiple Accounts, beginning with the Spring ’21 release, the feature isn't automatically enabled. You must manually enable the setting for new scratch orgs. Enable the setting in one of these ways: update the Account Settings page in Setup, add the enableRelateContactsToMultipleAccounts setting to your scratch org definition file, or enable it via Metadata API.
Successfully created scratch org: 00D1j000000E4z8EAC, username: test-dhyglsiy5soa@example.com

Pushing source...
Job ID | 0Af1j00001VJaKbCAL
SOURCE PROGRESS | ████████████████████████████████████████ | 110/110 Components
=== Pushed Source
STATE  FULL NAME                                              TYPE                        PROJECT PATH
─────  ─────────────────────────────────────────────────────  ──────────────────────────  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Add    Quiz                                                   CustomApplication           src\main\default\applications\Quiz.app-meta.xml
Add    QuizAbstractDataService                                ApexClass                   src\main\default\classes\QuizAbstractDataService.cls
Add    QuizAbstractDataService                                ApexClass                   src\main\default\classes\QuizAbstractDataService.cls-meta.xml
Add    QuizAnswer                                             ApexClass                   src\main\default\classes\QuizAnswer.cls
Add    QuizAnswer                                             ApexClass                   src\main\default\classes\QuizAnswer.cls-meta.xml
Add    QuizAnswerRestResource                                 ApexClass                   src\main\default\classes\QuizAnswerRestResource.cls

||||||||||||||All apex class in between|||||||||||

Add    QuizSettingsTest                                       ApexClass                   src\test\default\classes\QuizSettingsTest.cls-meta.xml
Add    QuizTestUtils                                          ApexClass                   src\test\default\classes\QuizTestUtils.cls
Add    QuizTestUtils                                          ApexClass                   src\test\default\classes\QuizTestUtils.cls-meta.xml

Assigning permissions...
=== Failures
Username                       Error Message
─────────────────────────────  ───────────────────────────────────────────────────────────────────────
test-dhyglsiy5soa@example.com  Permission set "Q" not found in target org. Do you need to push source?

Importing data...
ERROR running force:data:tree:import:  We couldn't process your request because you don't have access to Label__c on Quiz_Question__c. To learn more about field-level security, visit Tips and Hints for Page Layouts and Field-Level Security in our Developer Documentation.
Installation failed.

Generating user password...
Successfully set the password "xxxxxxxxxxxx" for user test-dhyglsiy5soa@example.com.
You can see the password again by running "sfdx force:user:display -u test-dhyglsiy5soa@example.com".

Installation completed.

Access org 00D1j000000E4z8EAC as user test-dhyglsiy5soa@example.com with the following URL: https://customization-force-3605-dev-ed.cs102.my.salesforce.com/secur/frontdoor.jsp?sid=00D1j000000E4z8!ARkAQPjYJbIODmi5WJfPSBRsdWSvOXBLHPylUe98m.86cIK8N2meNMHmNP9HxE8SOgJZDoOvwcKn7jXWwHzzFxJ_hBKN5teQ&retURL=%2Flightning%2Fsetup%2FSecurityremoteProxy%2Fhome

_Short summary of what is going on or to provide context_.
There is no App available in Apps
![image](https://user-images.githubusercontent.com/5717806/134035949-2c117efb-f0a4-4262-88a2-066852c9048c.png)

To solve this problem I tried to add App so I given App permission to system admin from control panel
But still getting this error
![image](https://user-images.githubusercontent.com/5717806/134036401-3a662348-08b0-4f23-aff0-2966269fe04d.png)

Could you please help me in resolving this error and to make App run on Dev?

**Comment by pozil** [comment]
Hi @sandeepepita, thanks for your interest in the quiz app and for providing the logs along with your issue.
Looking at those, I see that the error comes from the permission set assignment:
> test-dhyglsiy5soa@example.com Permission set "Q" not found in target org. Do you need to push source?

What's strange is that the install script use `Quiz_Host` and not `Q` as the permission set name:
https://github.com/fostive/quiz-host-app/blob/2829cadbfedd4e1ddf62b001db42ef57393f6cce/install-dev.bat#L37

Did you modify the install script?

**Comment by sandeepepita** [comment]
Hello @pozil 
Thank you for reply.
No i didn't modify anything, I just followed given steps. I am kind of blocked at this stage. 
Also is it possible to install it directly on sandbox instead of scratch org? Could you please help me in proceeding further?

**Comment by pozil** [comment]
I recommend that you resume the installation on your scratch org by manually running the CLI commands that failed.

Open a terminal in the project `quiz-host-app` directory and run these these one at the time:
```sh
sfdx force:user:permset:assign -n Quiz_Host

sfdx force:data:tree:import -p data/sample/plan.json

sfdx force:org:open
```

BTW I noticed that your scratch org user password was visible in clear in the issue description so I edited your logs.

**Comment by sandeepepita** [comment]
Hello Pozil,

Thank you for reply.
Thanks for deleting password... I haven't noticed that while posting question.
Regarding manual installation I already tried that and got similar error.

![image](https://user-images.githubusercontent.com/5717806/134339797-09fd8793-0313-4f31-943c-3e01fdabf81f.png)

**Comment by pozil** [comment]
That is really strange. I wonder why the name of the permission set is cut on the first letter.
Try to [update your CLI](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_update_cli.htm) maybe? Current version is around `7.118.x`.

If that doesn't solve the issue, you can assign the permission set manually in your Org:
1. go to **Setup > Users > Permission Sets**.
1. click on **Quiz Host** then **Manage Assignements**
1. add the permission set to your user

Once this is done you'll need to run the CLI command to deploy the sample data:
```
sfdx force:data:tree:import -p data/sample/plan.json
```

**Comment by sandeepepita** [comment]
I tried with the way you explained and imported sample data successfully but its not showing login form for players on heruku
![image](https://user-images.githubusercontent.com/5717806/134355298-f37ec353-a800-4eb4-8460-ecb718d11948.png)

When I click on   Reset button 
![image](https://user-images.githubusercontent.com/5717806/134355428-5417d0f5-4d39-4eac-a5dd-cbf818db1353.png)


at that time form(registration form) for players appear for 1 second and disappear again.

**Comment by pozil** [comment]
Can your open your browser's developer console on both pages and check if there are errors?

**Comment by sandeepepita** [comment]
Yes
![image](https://user-images.githubusercontent.com/5717806/134366775-4dcbe129-39c5-4179-93b7-bcfdce532c15.png)

And  for Player on herokuapp

![image](https://user-images.githubusercontent.com/5717806/134366821-c0307522-3219-4000-abc1-d02a901a584a.png)

**Comment by pozil** [comment]
Looking at your logs, there's an error on the Heroku app.
Can you expand the HTTP 500 error in the second screenshot and share your Heroku logs?

**Comment by sandeepepita** [comment]
OK
here it is
![image](https://user-images.githubusercontent.com/5717806/134369827-b64309a5-ee2b-4584-b074-e241ef4de48e.png)

**Comment by sandeepepita** [comment]
Yes
Logs from Heroku

Application Logs
2021-09-23T08:42:03.859581+00:00 app[web.1]:     at HttpApi.getError (/app/node_modules/jsforce/lib/http-api.js:250:13)
2021-09-23T08:42:03.859582+00:00 app[web.1]:     at /app/node_modules/jsforce/lib/http-api.js:95:22
2021-09-23T08:42:03.859582+00:00 app[web.1]:     at tryCallOne (/app/node_modules/promise/lib/core.js:37:12)
2021-09-23T08:42:03.859583+00:00 app[web.1]:     at /app/node_modules/promise/lib/core.js:123:15
2021-09-23T08:42:03.859583+00:00 app[web.1]:     at flush (/app/node_modules/asap/raw.js:50:29)
2021-09-23T08:42:03.859583+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:78:11) {
2021-09-23T08:42:03.859584+00:00 app[web.1]:   errorCode: 'INVALID_TYPE'
2021-09-23T08:42:03.859584+00:00 app[web.1]: }
2021-09-23T08:42:03.860629+00:00 heroku[router]: at=info method=GET path="/api/quiz-sessions" host=developerquizapp.herokuapp.com request_id=09bf2a1b-5569-4642-8f27-be46fae32aec fwd="163.5.55.50" dyno=web.1 connect=0ms service=194ms status=500 bytes=276 protocol=https
2021-09-23T08:42:11.833180+00:00 heroku[router]: at=info method=GET path="/" host=developerquizapp.herokuapp.com request_id=9d663e0a-8434-4835-96c1-5a4bd2f68e6e fwd="85.222.158.8" dyno=web.1 connect=0ms service=3ms status=200 bytes=881 protocol=https

**Comment by pozil** [comment]
Hi @sandeepepita, thanks for the logs, this is the error that's causing your issue:
```
2021-09-23T08:43:11.633026+00:00 app[web.1]: sObject type 'sfqz__Quiz_Session__c' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names.
```

You forgot to change the value of the `SF_NAMESPACE` Heroku environment variable (install step 2.4) and the player app is trying to access the Salesforce org object with the `sfqz` namespace prefix (that's the expected behavior for an installation with the Salesforce package). In your case, you're using a scratch org installation so you need to disable the namespace by changing the value of the `SF_NAMESPACE` variable to an empty string.
Once you have done that, restart the Heroku Dyno and things should be back to normal.

**Comment by sandeepepita** [comment]
Hello @pozil,
Thanks a looooot... :) finally its working...

**Comment by pozil** [comment]
Nice, I'm glad that we figured it out. Thanks for using the quiz app.
