### ISSUE TITLE
Heroku Deployment Fails

### ISSUE THREAD

**Issue by ikimmoweb** [fostive/quiz-host-app#90]
### Summary

Heroku Deployment Fails

### Steps To Reproduce:

1. Try to deploy the app to Heroku.

### Expected result

Successful deployment

### Actual result

Deployment failed.

### Additional information
![image](https://user-images.githubusercontent.com/82382646/138700374-c2f30b21-bd3d-46e8-b471-9687fb33699d.png)

I have doubled checked the parameters I set to the project and it looks ok, maybe I am missing something else.
I also see this warning from Heroku could that be the reason ?
![image](https://user-images.githubusercontent.com/82382646/138702815-a742aaad-4f71-4980-b50c-088b07589a4c.png)
_Feel free to attach a screenshot or code snippets_.

**Comment by pozil** [comment]
Hi @ikimmoweb, thanks for reporting this and sorry for the delay in my response (I was on holiday).
I've addressed the issue with updates to the game host and player apps.
