### ISSUE TITLE
Quiz Host App: Bug report

### ISSUE THREAD

**Issue by davidgfreeman** [fostive/quiz-host-app#97]
### Summary

Contact information: David Freeman, Salesforce Technical Architect, dfreeman@salesforce.com

_Short summary of what is going on or to provide context_.

Tested with iPhone 12 (iOS 15.4.1), Android Galaxy S21+ (v12), MacBook Pro 2020 (iOS 12.3.1), and Chromebook (v100.0.4896.133)

-Cannot have an apostrophe ( ' ) in the name when registering for quiz; e.g. cannot have ( David's Chromebook ), but can have ( Davids Chromebook ). (Minor problem)

-Intermittently, some devices show "Wait for question." when the quiz is started.

-Intermittently, all devices show "Wait for question." when the question is shown on the big screen and the timer counts down.

### App Version

Host app version (see bottom of host game page):
x.y.z

v2.7.0

Player app version (see bottom of player registration page):
x.y.z

v2.1.1

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

Two issues...

-Once everyone registers and the quiz is started, a device or device(s) will sit at "Waiting for how to start game." while the other devices show the question properly. If the user with the "stalled" device refreshes, the question is shown, but typically too late to answer and they see "You didn't answer in time.". This happens intermittently. 

-When proceeding to the next question by clicking ( Next ), all devices show "Wait for question." on their screens while the question is shown on the main screen and the timer winds down. I have the question timer set to 15 seconds. After about 12 seconds, the question is shown on devices, but this only gives about 3 seconds to answer.

### Expected result

_Describe what should have happened_.

Self-explanatory given above scenario in Steps to Reproduce. 

### Actual result

_Describe what actually happened instead_.

Self-explanatory given above scenario in Steps to Reproduce. 

### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by pozil** [comment]
Hi @davidgfreeman, thanks for the feedback.
I'll work on the username apostrophe issue but there's not much I can do on the other issues related to timing.
I've already noticed that the WebSockets that helps to sync the game are inconsistently received on mobile devices. The key factor seems to be the distance between the players and the location on the Heroku datacenter on which the player app is deployed.

**Comment by pozil** [comment]
Also, if the mobile devices are running on 4G or 5G, the mobile operator has an impact on latency.
This is a related issue: https://github.com/fostive/quiz-player-app/issues/35

**Comment by davidgfreeman** [comment]
Thank you for the quick response! And understood.

David Freeman


On May 12, 2022, at 11:14, Philippe Ozil ***@***.******@***.***>> wrote:



Also, if the mobile devices are running on 4G or 5G, the mobile operator has an impact on latency.
This is a related issue: fostive/quiz-player-app#35<https://github.com/fostive/quiz-player-app/issues/35>

**Comment by pozil** [comment]
Hey @davidgfreeman, I just fixed the apostrophe issue. All you have to do is update to the latest version of the player app (v2.1.2).

**Comment by davidgfreeman** [comment]
Philippe,

The app is awesome! And really appreciated.

David

On May 17, 2022, at 11:11, Philippe Ozil ***@***.******@***.***>> wrote:



Hey @davidgfreeman<https://github.com/davidgfreeman>, I just fixed the apostrophe issue. All you have to do is update to the latest version of the player app (v2.1.2).
